const Grocery = () => {
    return(<div>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vel eros donec ac odio tempor orci dapibus. Integer feugiat scelerisque varius morbi enim. Purus non enim praesent elementum. At tempor commodo ullamcorper a. Ipsum dolor sit amet consectetur adipiscing. Feugiat in ante metus dictum at tempor commodo ullamcorper a. Facilisis mauris sit amet massa vitae. Sed risus ultricies tristique nulla. Feugiat nisl pretium fusce id velit ut. Nulla at volutpat diam ut venenatis tellus. Urna condimentum mattis pellentesque id. Vulputate sapien nec sagittis aliquam malesuada. Iaculis nunc sed augue lacus viverra vitae congue eu consequat.
<br/>
Tempor nec feugiat nisl pretium fusce id. Et magnis dis parturient montes. Mauris in aliquam sem fringilla ut morbi tincidunt augue interdum. Euismod nisi porta lorem mollis aliquam. Nisl nunc mi ipsum faucibus. Cursus turpis massa tincidunt dui ut ornare lectus. Pulvinar mattis nunc sed blandit libero volutpat sed cras. Senectus et netus et malesuada fames ac turpis. Viverra maecenas accumsan lacus vel facilisis volutpat est velit. Augue mauris augue neque gravida. In aliquam sem fringilla ut morbi tincidunt augue interdum. Adipiscing elit ut aliquam purus sit amet luctus venenatis lectus. Duis ultricies lacus sed turpis. Proin fermentum leo vel orci.
<br/>

Pulvinar neque laoreet suspendisse interdum consectetur libero id. Morbi blandit cursus risus at ultrices mi. Et tortor consequat id porta nibh venenatis. Eu non diam phasellus vestibulum. Pharetra diam sit amet nisl suscipit adipiscing bibendum. Elit pellentesque habitant morbi tristique. Imperdiet nulla malesuada pellentesque elit. Rhoncus mattis rhoncus urna neque viverra justo nec ultrices. Quam quisque id diam vel quam elementum pulvinar etiam non. Vitae proin sagittis nisl rhoncus mattis rhoncus urna neque. Quam viverra orci sagittis eu volutpat. Dignissim convallis aenean et tortor. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Arcu dui vivamus arcu felis bibendum ut tristique et. Nunc mattis enim ut tellus elementum sagittis vitae. Risus feugiat in ante metus dictum at. Risus nec feugiat in fermentum posuere urna nec.
<br/>

Lacus sed turpis tincidunt id aliquet risus feugiat in ante. Eu turpis egestas pretium aenean pharetra magna ac placerat vestibulum. Massa enim nec dui nunc mattis. Sit amet aliquam id diam maecenas ultricies mi. At lectus urna duis convallis convallis tellus. Arcu ac tortor dignissim convallis aenean. Imperdiet proin fermentum leo vel. Dictum at tempor commodo ullamcorper a lacus vestibulum. At auctor urna nunc id cursus. Malesuada fames ac turpis egestas. Neque aliquam vestibulum morbi blandit cursus risus at ultrices. Amet massa vitae tortor condimentum. Cursus in hac habitasse platea dictumst quisque. Laoreet suspendisse interdum consectetur libero id faucibus nisl tincidunt eget. Egestas sed tempus urna et pharetra pharetra. Lacus suspendisse faucibus interdum posuere lorem. Sit amet consectetur adipiscing elit ut aliquam purus.
<br/>

Aliquet enim tortor at auctor urna nunc id cursus metus. A diam maecenas sed enim ut sem viverra. Mauris pharetra et ultrices neque ornare aenean. Semper viverra nam libero justo. Metus aliquam eleifend mi in nulla posuere sollicitudin. Pellentesque adipiscing commodo elit at imperdiet dui. Eu nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper. Lacus sed turpis tincidunt id aliquet risus. Fusce id velit ut tortor pretium viverra suspendisse potenti nullam. Scelerisque eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Pretium nibh ipsum consequat nisl. Odio facilisis mauris sit amet. Mauris in aliquam sem fringilla ut morbi tincidunt augue. Et molestie ac feugiat sed lectus vestibulum mattis ullamcorper. Imperdiet sed euismod nisi porta lorem mollis aliquam ut. Platea dictumst quisque sagittis purus sit amet volutpat consequat.
    </div>)
}

export default Grocery;